# Generated by Django 5.0.10 on 2025-12-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('admin_group_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('currency_symbol', models.CharField(default='₽', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Settings',
                'verbose_name_plural': 'Bot Settings',
            },
        ),
    ]
