# Generated by Django 5.0.10 on 2025-12-19 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_user_id", models.BigIntegerField(db_index=True)),
                ("mode", models.CharField(default="pickup", max_length=20)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("PAID", "PAID"),
                            ("PREPARING", "PREPARING"),
                            ("READY", "READY"),
                            ("ON_THE_WAY", "ON_THE_WAY"),
                            ("DELIVERED", "DELIVERED"),
                            ("CANCELED", "CANCELED"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=120)),
                ("price", models.IntegerField()),
                ("qty", models.IntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
