# Generated by Django 5.0.10 on 2025-12-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'PENDING_PAYMENT'), ('PAID', 'PAID'), ('PREPARING', 'PREPARING'), ('READY', 'READY'), ('ON_THE_WAY', 'ON_THE_WAY'), ('DELIVERED', 'DELIVERED'), ('CANCELED', 'CANCELED'), ('EXPIRED', 'EXPIRED')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
